name = "dd-api-cf"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
DANDAN_APP_ID = "s8zi9cvbw9"
DANDAN_APP_SECRET = "24QkxXdVGF4k3RIVPHDNIbsUY4GYPtxF"

[[rules]]
type = "ESModule"
globs = ["**/*.ts"]
